csm: modify o11y test to use proxyless bootstrap injector
grpc/psm-interop pull request #141
Opened 2024-11-26 18:56 UTC by arvindbr8

As part of CSM Gateway for Mesh GA - we have already implemented a Proxyless Bootstrap Injector in GCP which will allow clusters that are onboarded to CSM Gateway for Mesh to get the following injected into the pod with the right labels:

1. initContainer with TD Bootstrap Injector + volume Mount where the config output is generated
2. CSM O11y related labels and envvars. 

The test cluster also had to be updated to follow the new onboarding steps. I will create a CL internally to update the cluster creation script

2024-11-26 21:56 UTC, arvindbr8 commented
Testing the new cluster + test driver [here](http://sponge2/659c620f-02a2-4cca-aafe-0864d2e9e2b2)

2024-11-26 23:06 UTC, arvindbr8 reviewed
The last one failed for connectivity issues. I was able to verify that the injector added the CSM o11y env vars and also the bootstrap config to the volume mount. 

Kicking off another run of the test suite:

- [ ] [grpc/core/master/linux/psm-csm-python](http://fusion2/e93ea3e0-1ca1-411f-99e8-3bbee32e91f6)

2024-12-02 21:16 UTC, sergiitk requested changes
Ideally I'd like to avoid creating new templates, and just configure everything with deployment args. Let's talk IRL about how we can achieve that.

2024-12-02 22:49 UTC, arvindbr8 commented
[latest run](https://fusion2.corp.google.com/invocations/849a8ecc-f061-49d9-ba56-45e9e5db633f/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fpsm-csm;config=default/log) after modifying api version

2024-12-04 21:06 UTC, sergiitk approved these changes
LGTM if full CSM suite passes

2024-12-04 21:06 UTC, sergiitk commented on tests/gamma/csm_observability_test_with_injection.py
> +# Copyright 2023 gRPC authors.
```suggestion
# Copyright 2024 gRPC authors.
```

2024-12-04 21:06 UTC, sergiitk commented on kubernetes-manifests/gamma/server.deployment.yaml
> +          # TODO:(lsafran) test without this when ipv6 HC fw rules are in place
update this so it doesn't render

2024-12-04 21:12 UTC, arvindbr8 commented
Running the entire suite again - 
- [ ] [grpc/core/v1.68.x/branch/linux/psm-csm](https://source.cloud.google.com/results/invocations/3e3a284a-857d-4a1a-9591-d78efff9008e)

2024-12-04 22:53 UTC, merged